[2025-06-09T14:15:04.924+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-09T14:15:04.996+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_pipeline_branching_dag.check_kafka_connection manual__2025-06-09T14:15:04.176610+00:00 [queued]>
[2025-06-09T14:15:05.021+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_pipeline_branching_dag.check_kafka_connection manual__2025-06-09T14:15:04.176610+00:00 [queued]>
[2025-06-09T14:15:05.023+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-06-09T14:15:05.046+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_kafka_connection> on 2025-06-09 14:15:04.176610+00:00
[2025-06-09T14:15:05.065+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2436) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-09T14:15:05.069+0000] {standard_task_runner.py:63} INFO - Started process 2437 to run task
[2025-06-09T14:15:05.068+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kafka_pipeline_branching_dag', 'check_kafka_connection', 'manual__2025-06-09T14:15:04.176610+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/kafka_pipeline_dag.py', '--cfg-path', '/tmp/tmpitdbyulb']
[2025-06-09T14:15:05.073+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask check_kafka_connection
[2025-06-09T14:15:05.124+0000] {task_command.py:426} INFO - Running <TaskInstance: kafka_pipeline_branching_dag.check_kafka_connection manual__2025-06-09T14:15:04.176610+00:00 [running]> on host 4e91ff50f4f4
[2025-06-09T14:15:05.235+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_pipeline_branching_dag' AIRFLOW_CTX_TASK_ID='check_kafka_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T14:15:04.176610+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-09T14:15:04.176610+00:00'
[2025-06-09T14:15:05.237+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-09T14:15:05.249+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-06-09T14:15:05.252+0000] {python.py:237} INFO - Done. Returned value was: kafka_available
[2025-06-09T14:15:05.253+0000] {branch.py:36} INFO - Branch into kafka_available
[2025-06-09T14:15:05.254+0000] {skipmixin.py:178} INFO - Following branch kafka_available
[2025-06-09T14:15:05.282+0000] {skipmixin.py:246} INFO - Skipping tasks [('kafka_connection_failed', -1)]
[2025-06-09T14:15:05.322+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-09T14:15:05.355+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=kafka_pipeline_branching_dag, task_id=check_kafka_connection, run_id=manual__2025-06-09T14:15:04.176610+00:00, execution_date=20250609T141504, start_date=20250609T141504, end_date=20250609T141505
[2025-06-09T14:15:05.379+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-09T14:15:05.410+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-09T14:15:05.412+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
