[2025-06-08T14:30:02.245+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T14:30:02.269+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: master_pipeline_with_es_guard.check_elasticsearch_soft scheduled__2025-06-08T14:00:00+00:00 [queued]>
[2025-06-08T14:30:02.278+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: master_pipeline_with_es_guard.check_elasticsearch_soft scheduled__2025-06-08T14:00:00+00:00 [queued]>
[2025-06-08T14:30:02.278+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-08T14:30:02.298+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_elasticsearch_soft> on 2025-06-08 14:00:00+00:00
[2025-06-08T14:30:02.307+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2096) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-08T14:30:02.309+0000] {standard_task_runner.py:63} INFO - Started process 2101 to run task
[2025-06-08T14:30:02.307+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'master_pipeline_with_es_guard', 'check_elasticsearch_soft', 'scheduled__2025-06-08T14:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpfx_0olek']
[2025-06-08T14:30:02.310+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask check_elasticsearch_soft
[2025-06-08T14:30:02.385+0000] {task_command.py:426} INFO - Running <TaskInstance: master_pipeline_with_es_guard.check_elasticsearch_soft scheduled__2025-06-08T14:00:00+00:00 [running]> on host 5492e8ecb5c1
[2025-06-08T14:30:02.485+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='panshul' AIRFLOW_CTX_DAG_ID='master_pipeline_with_es_guard' AIRFLOW_CTX_TASK_ID='check_elasticsearch_soft' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T14:00:00+00:00'
[2025-06-08T14:30:02.486+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T14:30:02.504+0000] {logging_mixin.py:188} INFO - ‚ùå ES request failed: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa9bd0b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-06-08T14:30:02.506+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-08T14:30:02.507+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T14:30:02.517+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=master_pipeline_with_es_guard, task_id=check_elasticsearch_soft, run_id=scheduled__2025-06-08T14:00:00+00:00, execution_date=20250608T140000, start_date=20250608T143002, end_date=20250608T143002
[2025-06-08T14:30:02.575+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-08T14:30:02.602+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-08T14:30:02.604+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
