[2025-06-10T12:29:19.089+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-10T12:29:19.115+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_pipeline_branching_dag.check_kafka_connection manual__2025-06-10T12:29:18.091636+00:00 [queued]>
[2025-06-10T12:29:19.125+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_pipeline_branching_dag.check_kafka_connection manual__2025-06-10T12:29:18.091636+00:00 [queued]>
[2025-06-10T12:29:19.126+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-06-10T12:29:19.138+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_kafka_connection> on 2025-06-10 12:29:18.091636+00:00
[2025-06-10T12:29:19.148+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=10009) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-10T12:29:19.150+0000] {standard_task_runner.py:63} INFO - Started process 10011 to run task
[2025-06-10T12:29:19.149+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kafka_pipeline_branching_dag', 'check_kafka_connection', 'manual__2025-06-10T12:29:18.091636+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/kafka_pipeline_dag.py', '--cfg-path', '/tmp/tmpyet9nezz']
[2025-06-10T12:29:19.151+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask check_kafka_connection
[2025-06-10T12:29:19.184+0000] {task_command.py:426} INFO - Running <TaskInstance: kafka_pipeline_branching_dag.check_kafka_connection manual__2025-06-10T12:29:18.091636+00:00 [running]> on host 4e91ff50f4f4
[2025-06-10T12:29:19.241+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_pipeline_branching_dag' AIRFLOW_CTX_TASK_ID='check_kafka_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-06-10T12:29:18.091636+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-10T12:29:18.091636+00:00'
[2025-06-10T12:29:19.242+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-10T12:29:19.250+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-06-10T12:29:19.251+0000] {python.py:237} INFO - Done. Returned value was: kafka_available
[2025-06-10T12:29:19.251+0000] {branch.py:36} INFO - Branch into kafka_available
[2025-06-10T12:29:19.252+0000] {skipmixin.py:178} INFO - Following branch kafka_available
[2025-06-10T12:29:19.266+0000] {skipmixin.py:246} INFO - Skipping tasks [('kafka_connection_failed', -1)]
[2025-06-10T12:29:19.288+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-10T12:29:19.314+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=kafka_pipeline_branching_dag, task_id=check_kafka_connection, run_id=manual__2025-06-10T12:29:18.091636+00:00, execution_date=20250610T122918, start_date=20250610T122919, end_date=20250610T122919
[2025-06-10T12:29:19.332+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-10T12:29:19.351+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-10T12:29:19.352+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
