[2025-06-07T19:31:33.572+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: producer_dag.run_producer_one_file scheduled__2025-06-07T19:00:00+00:00 [queued]>
[2025-06-07T19:31:33.576+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: producer_dag.run_producer_one_file scheduled__2025-06-07T19:00:00+00:00 [queued]>
[2025-06-07T19:31:33.576+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-06-07T19:31:33.585+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_producer_one_file> on 2025-06-07 19:00:00+00:00
[2025-06-07T19:31:33.588+0000] {standard_task_runner.py:60} INFO - Started process 200 to run task
[2025-06-07T19:31:33.591+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'producer_dag', 'run_producer_one_file', 'scheduled__2025-06-07T19:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpsnhbhu_7']
[2025-06-07T19:31:33.593+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask run_producer_one_file
[2025-06-07T19:31:33.626+0000] {task_command.py:423} INFO - Running <TaskInstance: producer_dag.run_producer_one_file scheduled__2025-06-07T19:00:00+00:00 [running]> on host 660bb7972175
[2025-06-07T19:31:33.684+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='panshul' AIRFLOW_CTX_DAG_ID='producer_dag' AIRFLOW_CTX_TASK_ID='run_producer_one_file' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-07T19:00:00+00:00'
[2025-06-07T19:31:33.685+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-07T19:31:33.686+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/kafka_client/producer_one_shot.py']
[2025-06-07T19:31:33.692+0000] {subprocess.py:86} INFO - Output:
[2025-06-07T19:31:34.480+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-07T19:31:34.481+0000] {subprocess.py:93} INFO -   File "/opt/***/kafka_client/producer_one_shot.py", line 6, in <module>
[2025-06-07T19:31:34.481+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-06-07T19:31:34.481+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2025-06-07T19:31:34.536+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-07T19:31:34.544+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-07T19:31:34.548+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=producer_dag, task_id=run_producer_one_file, execution_date=20250607T190000, start_date=20250607T193133, end_date=20250607T193134
[2025-06-07T19:31:34.554+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task run_producer_one_file (Bash command failed. The command returned a non-zero exit code 1.; 200)
[2025-06-07T19:31:34.596+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-07T19:31:34.605+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
