[2025-06-09T13:40:03.862+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-09T13:40:03.881+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_pipeline_branching_dag.check_kafka_connection manual__2025-06-09T13:40:03.148309+00:00 [queued]>
[2025-06-09T13:40:03.885+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_pipeline_branching_dag.check_kafka_connection manual__2025-06-09T13:40:03.148309+00:00 [queued]>
[2025-06-09T13:40:03.885+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-06-09T13:40:03.891+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_kafka_connection> on 2025-06-09 13:40:03.148309+00:00
[2025-06-09T13:40:03.895+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1403) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-09T13:40:03.896+0000] {standard_task_runner.py:63} INFO - Started process 1404 to run task
[2025-06-09T13:40:03.895+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kafka_pipeline_branching_dag', 'check_kafka_connection', 'manual__2025-06-09T13:40:03.148309+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/kafka_pipeline_dag.py', '--cfg-path', '/tmp/tmpnidp2t51']
[2025-06-09T13:40:03.897+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask check_kafka_connection
[2025-06-09T13:40:03.921+0000] {task_command.py:426} INFO - Running <TaskInstance: kafka_pipeline_branching_dag.check_kafka_connection manual__2025-06-09T13:40:03.148309+00:00 [running]> on host 4e91ff50f4f4
[2025-06-09T13:40:03.959+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_pipeline_branching_dag' AIRFLOW_CTX_TASK_ID='check_kafka_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T13:40:03.148309+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-09T13:40:03.148309+00:00'
[2025-06-09T13:40:03.959+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-09T13:40:03.966+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-06-09T13:40:03.966+0000] {python.py:237} INFO - Done. Returned value was: run_producer
[2025-06-09T13:40:03.966+0000] {branch.py:36} INFO - Branch into run_producer
[2025-06-09T13:40:03.967+0000] {skipmixin.py:178} INFO - Following branch run_producer
[2025-06-09T13:40:03.976+0000] {skipmixin.py:246} INFO - Skipping tasks [('kafka_connection_failed', -1)]
[2025-06-09T13:40:03.987+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-09T13:40:03.996+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=kafka_pipeline_branching_dag, task_id=check_kafka_connection, run_id=manual__2025-06-09T13:40:03.148309+00:00, execution_date=20250609T134003, start_date=20250609T134003, end_date=20250609T134003
[2025-06-09T13:40:04.037+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-09T13:40:04.052+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-09T13:40:04.053+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
