[2025-06-09T14:08:38.917+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-09T14:08:38.938+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_pipeline_branching_dag.check_kafka_connection manual__2025-06-09T14:08:38.322124+00:00 [queued]>
[2025-06-09T14:08:38.942+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_pipeline_branching_dag.check_kafka_connection manual__2025-06-09T14:08:38.322124+00:00 [queued]>
[2025-06-09T14:08:38.943+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-06-09T14:08:38.950+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_kafka_connection> on 2025-06-09 14:08:38.322124+00:00
[2025-06-09T14:08:38.954+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2288) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-09T14:08:38.955+0000] {standard_task_runner.py:63} INFO - Started process 2289 to run task
[2025-06-09T14:08:38.954+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kafka_pipeline_branching_dag', 'check_kafka_connection', 'manual__2025-06-09T14:08:38.322124+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/kafka_pipeline_dag.py', '--cfg-path', '/tmp/tmpc70hrmdh']
[2025-06-09T14:08:38.956+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask check_kafka_connection
[2025-06-09T14:08:38.981+0000] {task_command.py:426} INFO - Running <TaskInstance: kafka_pipeline_branching_dag.check_kafka_connection manual__2025-06-09T14:08:38.322124+00:00 [running]> on host 4e91ff50f4f4
[2025-06-09T14:08:39.029+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_pipeline_branching_dag' AIRFLOW_CTX_TASK_ID='check_kafka_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T14:08:38.322124+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-09T14:08:38.322124+00:00'
[2025-06-09T14:08:39.029+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-09T14:08:39.037+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-06-09T14:08:39.038+0000] {python.py:237} INFO - Done. Returned value was: run_producer
[2025-06-09T14:08:39.038+0000] {branch.py:36} INFO - Branch into run_producer
[2025-06-09T14:08:39.038+0000] {skipmixin.py:178} INFO - Following branch run_producer
[2025-06-09T14:08:39.046+0000] {skipmixin.py:246} INFO - Skipping tasks [('kafka_available', -1), ('kafka_connection_failed', -1)]
[2025-06-09T14:08:39.056+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-09T14:08:39.064+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=kafka_pipeline_branching_dag, task_id=check_kafka_connection, run_id=manual__2025-06-09T14:08:38.322124+00:00, execution_date=20250609T140838, start_date=20250609T140838, end_date=20250609T140839
[2025-06-09T14:08:39.098+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-09T14:08:39.109+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-09T14:08:39.111+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
