[2025-06-08T14:21:23.366+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T14:21:23.390+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: master_pipeline_with_es_guard.run_consumer manual__2025-06-08T14:21:21.384220+00:00 [queued]>
[2025-06-08T14:21:23.395+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: master_pipeline_with_es_guard.run_consumer manual__2025-06-08T14:21:21.384220+00:00 [queued]>
[2025-06-08T14:21:23.396+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-08T14:21:23.405+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_consumer> on 2025-06-08 14:21:21.384220+00:00
[2025-06-08T14:21:23.412+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1959) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-08T14:21:23.414+0000] {standard_task_runner.py:63} INFO - Started process 1963 to run task
[2025-06-08T14:21:23.413+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'master_pipeline_with_es_guard', 'run_consumer', 'manual__2025-06-08T14:21:21.384220+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpiuolm5gy']
[2025-06-08T14:21:23.415+0000] {standard_task_runner.py:91} INFO - Job 51: Subtask run_consumer
[2025-06-08T14:21:23.457+0000] {task_command.py:426} INFO - Running <TaskInstance: master_pipeline_with_es_guard.run_consumer manual__2025-06-08T14:21:21.384220+00:00 [running]> on host 5492e8ecb5c1
[2025-06-08T14:21:23.543+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='panshul' AIRFLOW_CTX_DAG_ID='master_pipeline_with_es_guard' AIRFLOW_CTX_TASK_ID='run_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T14:21:21.384220+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T14:21:21.384220+00:00'
[2025-06-08T14:21:23.544+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T14:21:23.558+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T14:21:23.560+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/kafka_client/consumer_***.py']
[2025-06-08T14:21:23.574+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T14:21:25.498+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,498 - INFO - âœ… spaCy model loaded successfully
[2025-06-08T14:21:25.526+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,525 - INFO - âœ… Geolocator initialized
[2025-06-08T14:21:25.660+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,660 - INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.20.0.4', 29092)]>: connecting to kafka:29092 [('172.20.0.4', 29092) IPv4]
[2025-06-08T14:21:25.662+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,660 - INFO - Probing node bootstrap-0 broker version
[2025-06-08T14:21:25.663+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,661 - INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.20.0.4', 29092)]>: Connection complete.
[2025-06-08T14:21:25.765+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,765 - INFO - Broker version identified as 2.6.0
[2025-06-08T14:21:25.766+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,765 - INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2025-06-08T14:21:25.766+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,765 - INFO - Updating subscribed topics to: ('covid-data',)
[2025-06-08T14:21:25.767+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,766 - INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.20.0.4', 29092)]>: connecting to kafka:29092 [('172.20.0.4', 29092) IPv4]
[2025-06-08T14:21:25.768+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,766 - INFO - Probing node bootstrap-0 broker version
[2025-06-08T14:21:25.768+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,767 - INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.20.0.4', 29092)]>: Connection complete.
[2025-06-08T14:21:25.870+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,869 - INFO - Broker version identified as 2.6.0
[2025-06-08T14:21:25.870+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,870 - INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2025-06-08T14:21:25.871+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,871 - INFO - ðŸš€ Kafka Consumer is running. Connecting to: kafka:29092
[2025-06-08T14:21:25.874+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,873 - INFO - Group coordinator for tweet-transformer-group is BrokerMetadata(nodeId='coordinator-1', host='kafka', port=29092, rack=None)
[2025-06-08T14:21:25.874+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,873 - INFO - Discovered coordinator coordinator-1 for group tweet-transformer-group
[2025-06-08T14:21:25.875+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,874 - INFO - Starting new heartbeat thread
[2025-06-08T14:21:25.875+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,874 - INFO - Revoking previously assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:21:25.875+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,875 - INFO - <BrokerConnection node_id=coordinator-1 host=kafka:29092 <connecting> [IPv4 ('172.20.0.4', 29092)]>: connecting to kafka:29092 [('172.20.0.4', 29092) IPv4]
[2025-06-08T14:21:25.876+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,875 - INFO - <BrokerConnection node_id=coordinator-1 host=kafka:29092 <connecting> [IPv4 ('172.20.0.4', 29092)]>: Connection complete.
[2025-06-08T14:21:25.876+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,875 - INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.20.0.4', 29092)]>: Closing connection.
[2025-06-08T14:21:25.977+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:25,977 - INFO - (Re-)joining group tweet-transformer-group
[2025-06-08T14:21:28.897+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:28,897 - INFO - Successfully joined group tweet-transformer-group with generation 5
[2025-06-08T14:21:28.899+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:28,897 - INFO - Updated partition assignment: []
[2025-06-08T14:21:28.900+0000] {subprocess.py:93} INFO - 2025-06-08 14:21:28,899 - INFO - Setting newly assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:26:25.933+0000] {subprocess.py:93} INFO - 2025-06-08 14:26:25,931 - INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.20.0.4', 29092)]>: connecting to kafka:29092 [('172.20.0.4', 29092) IPv4]
[2025-06-08T14:26:25.936+0000] {subprocess.py:93} INFO - 2025-06-08 14:26:25,932 - INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.20.0.4', 29092)]>: connecting to kafka:29092 [('172.20.0.4', 29092) IPv4]
[2025-06-08T14:26:25.937+0000] {subprocess.py:93} INFO - 2025-06-08 14:26:25,933 - INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.20.0.4', 29092)]>: Connection complete.
[2025-06-08T14:26:25.937+0000] {subprocess.py:93} INFO - 2025-06-08 14:26:25,934 - INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.20.0.4', 29092)]>: Connection complete.
[2025-06-08T14:26:25.937+0000] {subprocess.py:93} INFO - 2025-06-08 14:26:25,934 - INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.20.0.4', 29092)]>: Closing connection.
[2025-06-08T14:29:08.806+0000] {subprocess.py:93} INFO - 2025-06-08 14:29:08,805 - WARNING - Heartbeat failed for group tweet-transformer-group because it is rebalancing
[2025-06-08T14:29:08.809+0000] {subprocess.py:93} INFO - 2025-06-08 14:29:08,806 - INFO - Revoking previously assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:29:08.809+0000] {subprocess.py:93} INFO - 2025-06-08 14:29:08,806 - INFO - (Re-)joining group tweet-transformer-group
[2025-06-08T14:29:09.174+0000] {subprocess.py:93} INFO - 2025-06-08 14:29:09,174 - INFO - Successfully joined group tweet-transformer-group with generation 6
[2025-06-08T14:29:09.176+0000] {subprocess.py:93} INFO - 2025-06-08 14:29:09,174 - INFO - Updated partition assignment: []
[2025-06-08T14:29:09.176+0000] {subprocess.py:93} INFO - 2025-06-08 14:29:09,174 - INFO - Setting newly assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:30:06.276+0000] {subprocess.py:93} INFO - 2025-06-08 14:30:06,274 - WARNING - Heartbeat failed for group tweet-transformer-group because it is rebalancing
[2025-06-08T14:30:06.279+0000] {subprocess.py:93} INFO - 2025-06-08 14:30:06,275 - INFO - Revoking previously assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:30:06.279+0000] {subprocess.py:93} INFO - 2025-06-08 14:30:06,275 - INFO - (Re-)joining group tweet-transformer-group
[2025-06-08T14:30:07.154+0000] {subprocess.py:93} INFO - 2025-06-08 14:30:07,153 - INFO - Successfully joined group tweet-transformer-group with generation 7
[2025-06-08T14:30:07.154+0000] {subprocess.py:93} INFO - 2025-06-08 14:30:07,153 - INFO - Updated partition assignment: []
[2025-06-08T14:30:07.155+0000] {subprocess.py:93} INFO - 2025-06-08 14:30:07,153 - INFO - Setting newly assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:39:34.941+0000] {subprocess.py:93} INFO - 2025-06-08 14:39:34,939 - WARNING - Heartbeat failed for group tweet-transformer-group because it is rebalancing
[2025-06-08T14:39:34.943+0000] {subprocess.py:93} INFO - 2025-06-08 14:39:34,940 - INFO - Revoking previously assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:39:34.944+0000] {subprocess.py:93} INFO - 2025-06-08 14:39:34,940 - INFO - (Re-)joining group tweet-transformer-group
[2025-06-08T14:39:35.754+0000] {subprocess.py:93} INFO - 2025-06-08 14:39:35,754 - INFO - Successfully joined group tweet-transformer-group with generation 8
[2025-06-08T14:39:35.757+0000] {subprocess.py:93} INFO - 2025-06-08 14:39:35,754 - INFO - Updated partition assignment: []
[2025-06-08T14:39:35.759+0000] {subprocess.py:93} INFO - 2025-06-08 14:39:35,754 - INFO - Setting newly assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:46:00.372+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:00,370 - WARNING - Heartbeat failed for group tweet-transformer-group because it is rebalancing
[2025-06-08T14:46:00.375+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:00,371 - INFO - Revoking previously assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:46:00.375+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:00,371 - INFO - (Re-)joining group tweet-transformer-group
[2025-06-08T14:46:00.786+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:00,786 - INFO - Successfully joined group tweet-transformer-group with generation 9
[2025-06-08T14:46:00.787+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:00,786 - INFO - Updated partition assignment: []
[2025-06-08T14:46:00.787+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:00,786 - INFO - Setting newly assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:46:03.789+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:03,789 - WARNING - Heartbeat failed for group tweet-transformer-group because it is rebalancing
[2025-06-08T14:46:03.789+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:03,789 - INFO - Revoking previously assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:46:03.789+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:03,789 - INFO - (Re-)joining group tweet-transformer-group
[2025-06-08T14:46:08.295+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:08,295 - INFO - Successfully joined group tweet-transformer-group with generation 10
[2025-06-08T14:46:08.295+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:08,295 - INFO - Updated partition assignment: []
[2025-06-08T14:46:08.296+0000] {subprocess.py:93} INFO - 2025-06-08 14:46:08,295 - INFO - Setting newly assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:47:59.421+0000] {subprocess.py:93} INFO - 2025-06-08 14:47:59,419 - WARNING - Heartbeat failed for group tweet-transformer-group because it is rebalancing
[2025-06-08T14:47:59.424+0000] {subprocess.py:93} INFO - 2025-06-08 14:47:59,420 - INFO - Revoking previously assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:47:59.424+0000] {subprocess.py:93} INFO - 2025-06-08 14:47:59,420 - INFO - (Re-)joining group tweet-transformer-group
[2025-06-08T14:48:00.117+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:00,116 - INFO - Successfully joined group tweet-transformer-group with generation 11
[2025-06-08T14:48:00.117+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:00,117 - INFO - Updated partition assignment: []
[2025-06-08T14:48:00.118+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:00,117 - INFO - Setting newly assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:48:06.127+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:06,127 - WARNING - Heartbeat failed for group tweet-transformer-group because it is rebalancing
[2025-06-08T14:48:06.128+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:06,128 - INFO - Revoking previously assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:48:06.129+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:06,128 - INFO - (Re-)joining group tweet-transformer-group
[2025-06-08T14:48:06.133+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:06,133 - INFO - Successfully joined group tweet-transformer-group with generation 12
[2025-06-08T14:48:06.134+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:06,133 - INFO - Updated partition assignment: []
[2025-06-08T14:48:06.134+0000] {subprocess.py:93} INFO - 2025-06-08 14:48:06,133 - INFO - Setting newly assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:52:24.506+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:24,504 - WARNING - Heartbeat failed for group tweet-transformer-group because it is rebalancing
[2025-06-08T14:52:24.510+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:24,505 - INFO - Revoking previously assigned partitions set() for group tweet-transformer-group
[2025-06-08T14:52:24.510+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:24,505 - INFO - (Re-)joining group tweet-transformer-group
[2025-06-08T14:52:24.940+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:24,940 - INFO - Successfully joined group tweet-transformer-group with generation 13
[2025-06-08T14:52:24.941+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:24,940 - INFO - Updated partition assignment: []
[2025-06-08T14:52:24.941+0000] {subprocess.py:93} INFO - 2025-06-08 14:52:24,940 - INFO - Setting newly assigned partitions set() for group tweet-transformer-group
[2025-06-08T15:03:30.359+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-06-08T15:03:30.362+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-08T15:03:30.363+0000] {process_utils.py:132} INFO - Sending 15 to group 1963. PIDs of all processes in the group: [1965, 1963]
[2025-06-08T15:03:30.363+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1963
[2025-06-08T15:03:30.364+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-08T15:03:30.366+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-06-08T15:03:30.367+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T15:03:30.380+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 234, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-06-08T15:03:30.384+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=master_pipeline_with_es_guard, task_id=run_consumer, run_id=manual__2025-06-08T14:21:21.384220+00:00, execution_date=20250608T142121, start_date=20250608T142123, end_date=20250608T150330
[2025-06-08T15:03:30.395+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 51 for task run_consumer ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(master_pipeline_with_es_guard, run_consumer, manual__2025-06-08T14:21:21.384220+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'run_consumer', 'dag_id': 'master_pipeline_with_es_guard', 'run_id': 'manual__2025-06-08T14:21:21.384220+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 6, 8, 14, 21, 23, 390882, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 6, 8, 15, 3, 30, 383422, tzinfo=Timezone('UTC')), 'duration': 2526}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 1963)
[2025-06-08T15:03:30.421+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1963, status='terminated', exitcode=1, started='14:21:22') (1963) terminated with exit code 1
[2025-06-08T15:03:30.421+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1965, status='terminated', started='14:21:22') (1965) terminated with exit code None
